### ISSUE TITLE
AttributeError: module 'astroid.nodes' has no attribute 'Try'

### ISSUE THREAD

**Issue by quantumpacket** [pylint-dev/astroid#2247]
### Steps to reproduce

1. Install latest version of Pylint from git repo.
2. Run Pylint executable with no arguments.

### Current behavior

```
Traceback (most recent call last):
  File ".venv/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
             ^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pylint/__init__.py", line 34, in run_pylint
    PylintRun(argv or sys.argv[1:])
  File ".venv/lib/python3.11/site-packages/pylint/lint/run.py", line 153, in __init__
    linter.load_default_plugins()
  File ".venv/lib/python3.11/site-packages/pylint/lint/pylinter.py", line 363, in load_default_plugins
    checkers.initialize(self)
  File ".venv/lib/python3.11/site-packages/pylint/checkers/__init__.py", line 129, in initialize
    register_plugins(linter, __path__[0])
  File ".venv/lib/python3.11/site-packages/pylint/utils/utils.py", line 198, in register_plugins
    module = modutils.load_module_from_file(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/astroid/modutils.py", line 235, in load_module_from_file
    return load_module_from_modpath(modpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/astroid/modutils.py", line 220, in load_module_from_modpath
    return load_module_from_name(".".join(parts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/astroid/modutils.py", line 194, in load_module_from_name
    module = importlib.import_module(dotted_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anon/.local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File ".venv/lib/python3.11/site-packages/pylint/checkers/refactoring/__init__.py", line 16, in <module>
    from pylint.checkers.refactoring.refactoring_checker import RefactoringChecker
  File ".venv/lib/python3.11/site-packages/pylint/checkers/refactoring/refactoring_checker.py", line 30, in <module>
    NodesWithNestedBlocks = Union[nodes.Try, nodes.While, nodes.For, nodes.If]
                                  ^^^^^^^^^
AttributeError: module 'astroid.nodes' has no attribute 'Try'
```

### Expected behavior

Should run with no errors.

### Versions
                                      
**pylint:** 3.0.0b1
**astroid:** 3.0.0a7-dev0

**Comment by jacobtylerwalls** [comment]
Try upgrading astroid from 3.0.0a7-dev0 to 3.0.0a7.
