### ISSUE TITLE
Astroid 3.3.7: Crash when linting code using a cryptography module

### ISSUE THREAD

**Issue by mathiasertl** [pylint-dev/astroid#2662]
### Bug description

I'm getting a traceback when parsing trivial code using this cryptography module. This issue happens with astroid 3.3.7, but *not* with astroid 3.3.6!

When parsing the following ``a.py``:

```python
"""demo"""

from cryptography.hazmat.primitives.asymmetric import types

print(types.PublicKeyTypes)

```

### Command used

```shell
pylint a.py
```

### Pylint output

<details open>
    <summary>
        pylint crashed with a ``AstroidError`` and with the following stacktrace:
    </summary>

```python
Traceback (most recent call last):
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 788, in _lint_file
    check_astroid_module(module)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 1017, in check_astroid_module
    retval = self._check_astroid_module(
        ast_node, walker, rawcheckers, tokencheckers
    )
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 1069, in _check_astroid_module
    walker.walk(node)
    ~~~~~~~~~~~^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 90, in walk
    self.walk(child)
    ~~~~~~~~~^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/utils/ast_walker.py", line 87, in walk
    callback(astroid)
    ~~~~~~~~^^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/checkers/imports.py", line 578, in visit_importfrom
    self._add_imported_module(node, f"{imported_module.name}.{name}")
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/checkers/imports.py", line 1054, in _add_imported_module
    importedmodname = astroid.modutils.get_module_part(importedmodname)
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/modutils.py", line 430, in get_module_part
    file_from_modpath(
    ~~~~~~~~~~~~~~~~~^
        parts[starti : i + 1], path=path, context_file=context_file
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/modutils.py", line 325, in file_from_modpath
    return file_info_from_modpath(modpath, path, context_file).location
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/modutils.py", line 376, in file_info_from_modpath
    return _spec_from_modpath(modpath, path, context)
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/modutils.py", line 631, in _spec_from_modpath
    found_spec = spec.find_spec(modpath, path)
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/interpreter/_import/spec.py", line 476, in find_spec
    return _find_spec(tuple(modpath), tuple(path) if path else None)
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/interpreter/_import/spec.py", line 492, in _find_spec
    finder, spec = _find_spec_with_path(
                   ~~~~~~~~~~~~~~~~~~~~^
        _path, modname, module_parts, processed, submodule_path or path
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/interpreter/_import/spec.py", line 412, in _find_spec_with_path
    spec = finder_instance.find_module(
        modname, module_parts, processed, submodule_path
    )
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/astroid/interpreter/_import/spec.py", line 153, in find_module
    spec = importlib.util.find_spec(".".join((*processed, modname)))
  File "<frozen importlib.util>", line 111, in find_spec
ValueError: cryptography.hazmat.primitives.asymmetric.types.__spec__ is None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 752, in _lint_files
    self._lint_file(fileitem, module, check_astroid_module)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mati/git/mati/django-ca/.venv/lib/python3.13/site-packages/pylint/lint/pylinter.py", line 790, in _lint_file
    raise astroid.AstroidError from e
astroid.exceptions.AstroidError

```

</details>

### Expected behavior

No crash.

### Pylint version

```shell
pylint 3.3.2
astroid 3.3.7
Python 3.13.1 (main, Dec  6 2024, 18:40:43) [Clang 18.1.8 ]
```

### OS / Environment

linux (Linux)
python 3.13.1
astroid==3.3.7
cryptography==44.0.0
pylint==3.3.2

(not sure if relevant, probably not):

pylint-django==2.6.1
pylint-plugin-utils==0.8.2

**Comment by Pierre-Sassoulas** [comment]
Also thought about this considering the primer fail.

**Comment by hanwen-cluster** [comment]
3.3.7 is crashing for us too https://github.com/aws/aws-parallelcluster/actions/runs/12323336855/job/34799853104?pr=6617

**Comment by jacobtylerwalls** [comment]
@Pierre-Sassoulas Can you yank it? I don't have PyPI access.

**Comment by DanielNoord** [comment]
![image](https://github.com/user-attachments/assets/91583f0a-6ee1-41e5-bcad-5bf155e12855)

I can't seem to yank the release...

**Comment by Pierre-Sassoulas** [comment]
Sorry I was busy. I've yanked the package. What's your pypi's handle Jacob ? Also we should probably cleanup the pypi managers here to reduce the surface of attack.

**Comment by jacobtylerwalls** [comment]
Same username as GitHub

**Comment by DanielNoord** [comment]
Thanks @Pierre-Sassoulas 

I suddenly have some time tonight so will work on version 3 of the fix 😬🫠

**Comment by DanielNoord** [comment]
@jacobtylerwalls Are you able to reproduce this?

```shell
❯ python -m pip list
Package            Version
------------------ ---------------
astroid            3.3.7
attrs              24.3.0
black              24.10.0
cachetools         5.5.0
certifi            2024.12.14
cffi               1.17.1
cfgv               3.4.0
chardet            5.2.0
charset-normalizer 3.4.0
cli-ui             0.18.0
click              8.1.7
colorama           0.4.6
contributors-txt   1.0.0
coverage           7.6.9
cryptography       44.0.0
dill               0.3.9
distlib            0.3.9
docopt             0.6.2
execnet            2.1.1
filelock           3.16.1
gitdb              4.0.11
GitPython          3.1.43
identify           2.6.3
idna               3.10
iniconfig          2.0.0
isort              5.13.2
Jinja2             3.1.4
MarkupSafe         3.0.2
mccabe             0.7.0
mypy               1.13.0
mypy-extensions    1.0.0
nodeenv            1.9.1
nose               1.3.7
packaging          24.2
pathspec           0.12.1
pip                24.3.1
platformdirs       4.3.6
pluggy             1.5.0
pre_commit         4.0.1
py                 1.11.0
py-cpuinfo         9.0.0
pycparser          2.22
pyenchant          3.2.2
pylint             3.3.2
pyproject-api      1.8.0
PyQt6              6.8.0
PyQt6-Qt6          6.8.1
PyQt6_sip          13.9.1
pytest             8.3.4
pytest-benchmark   5.1.0
pytest-cov         6.0.0
pytest-timeout     2.3.1
pytest-xdist       3.6.1
python-dateutil    2.9.0.post0
PyYAML             6.0.2
regex              2024.11.6
requests           2.32.3
ruff               0.8.3
schema             0.7.7
setuptools         75.6.0
six                1.17.0
smmap              5.0.1
tabulate           0.9.0
tbump              6.11.0
tomlkit            0.11.8
towncrier          24.8.0
tox                4.23.2
types-setuptools   75.6.0.20241126
typing_extensions  4.12.2
Unidecode          1.3.8
urllib3            1.26.20
virtualenv         20.28.0
```

```shell
❯ python -m pylint --version
pylint 3.3.2
astroid 3.3.7
Python 3.13.1 (main, Dec 18 2024, 22:41:47) [Clang 16.0.0 (clang-1600.0.26.6)]
```

I can't with the current environment.
